name: Python application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Type check with mypy
        run: |
          poetry run python -m mypy -p zarrita
      - name: Download sample data
        run: |
          wget https://static.webknossos.org/data/l4_sample.zip
          unzip l4_sample.zip
      - name: Run tests
        run: |
          poetry run pytest -vv test_all.py
      - name: Run perf tests
        run: |
          TEST_SIZE=128,128,128 poetry run pytest -vv -s test_perf.py
